---
label: Project
hide_body: true
fields:
- name: naslov
  type: text
  config:
    required: false
  label: Naslov
- name: opis
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Opis
